drone-runners/drone-runner-aws

.drone.yml
Please show screen grabs of running the accepance tests. Testing is currently manual, but we will be adding automated testing soon.
- Tested the drone runner by running:
```bash
drone exec ?? more to come soon ...
```
```BASH
curl -d '{"id": "unique-stage-id","correlation_id":"abc1","pool_id":"ubuntu", "setup_request": {"network": {"id":"drone"}, "platform": { "os":"ubuntu" }}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/setup
```
- run a step on the instance:
```BASH
curl -d '{"id":"unique-stage-id","pool_id":"ubuntu","instance_id":"<INSTANCE ID>","correlation_id":"xyz2", "start_step_request":{"id":"step4", "image": …
```
=> Build mac binary

.drone.yml
=> (maint) publish happens after all checks pass

CHANGELOG.md
=> (maint) rc5_prep

internal/cloudinit/cloudinit.go, internal/drivers/google/option.go, internal/drivers/google/pool.go, internal/drivers/google/provider.go, internal/poolfile/config.go
=> [DRON-342] Implement Drone Runner for Windows on GCP

.drone.yml, command/config/config.go, command/daemon/daemon.go, command/delegate/delegate.go, command/exec.go, command/setup/setup.go, internal/drivers/amazon/option.go, internal/drivers/amazon/pool.go, internal/drivers/amazon/provider.go, internal/drivers/anka/option.go, internal/drivers/anka/pool.go, internal/drivers/anka/provider.go, internal/drivers/google/option.go, internal/drivers/google/pool.go, internal/drivers/google/provider.go, internal/drivers/manager.go, internal/drivers/pool.go, internal/drivers/vmfusion/options.go, internal/drivers/vmfusion/pool.go, internal/drivers/vmfusion/provider.go, internal/drivers/vmfusion/utils.go, internal/poolfile/config.go, test_files/compiler/drone_pool.yml, test_files/compiler/drone_ubuntu.yml, types/types.go
=> (DRON-324) simplify setup for google

CHANGELOG.md
=> prep for v1.0.0-rc.6

command/config/config.go
=> (fix) remove duplicate vpc from amazon

command/config/config.go, command/setup/setup.go, go.mod, go.sum, internal/cloudinit/cloudinit.go, internal/drivers/digitalocean/driver.go, internal/drivers/digitalocean/option.go, internal/drivers/digitalocean/option_test.go, internal/poolfile/config.go, types/types.go
```bash
./drone-runner-aws setup --digitalOceanPAT XXXX
INFO[0000] setup: using digital ocean                   
INFO[0000] no pool file provided                        
INFO[0000] in memory pool is using digitalocean         
INFO[0000] digitalocean: creating instance setup-testpool-1655379844  driver=digitalocean hibernate=false image=docker-18-04 pool=testpool
INFO[0001] digitalocean: instance created setup-testpool-1655379844  driver=digitalocean hibernate=false image=docker-18-04 pool=testpool
INFO[0003] digitalocean: firewall configured setup-testpool-1655379844  driver=digitalocean hibernate=false image=docker-18-04 pool=testpool
DEBU[0003] find instance network                         driver=digitalocean hibernate=false image=docker-18-04 name=setup-testpool-1655379844 …
```
=> (feat) initial implementation of the digitalocean driver

README.md, command/harness/destroy.go, command/harness/setup.go, internal/drivers/anka/driver.go, internal/drivers/vmfusion/driver.go
If provisioning fails of an instance - it will clean up the stage owner table
=> added clean up on provision failure

internal/drivers/google/driver.go, internal/poolfile/config.go
=> Fix support for gcp json key credentials

command/harness/dlite/cleanup.go
=> add return

command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, command/harness/pool.go, internal/drivers/amazon/driver.go, internal/drivers/digitalocean/driver.go
=> Cleanup pools on dlite termination

command/harness/setup.go
Find call checking stage owner exist doesn't return nil, it returns an empty object with no values set.
=> (bug) fixes issue were stage owner was never getting inserted

.drone.yml
=> (DRON-406) use binaries for github release on mac

CHANGELOG.md
=> (maint) rc9 prep

command/config/config.go, command/setup/setup.go, internal/drivers/ankabuild/driver.go, internal/poolfile/config.go
=> (feat) auto setup for Anka build

CHANGELOG.md
=> (maint) rc10 release

README.md
=> (fix) fix docker entry point

CHANGELOG.md
=> (maint) rc11 release prep

command/harness/setup.go, internal/drivers/amazon/driver.go, internal/drivers/anka/driver.go, internal/drivers/ankabuild/driver.go, internal/drivers/azure/driver.go, internal/drivers/digitalocean/driver.go, internal/drivers/google/driver.go, internal/drivers/manager.go, internal/drivers/pool.go, internal/drivers/vmfusion/driver.go
=> Add tags to a build instance

internal/drivers/google/option.go
=> Fix default network for gcp

CHANGELOG.md
=> rc-12 prep

command/harness/logger.go
=> (feat): make dlite logs compatible with stackdriver

command/config/config.go, command/harness/dlite/dlite.go
=> (feat) make poll interval and number of executors configurable

command/harness/setup.go, go.mod, go.sum
=> (fix): update go.mod

command/harness/destroy.go, command/harness/setup.go, internal/drivers/manager.go
=> (fix): improve logging

go.mod, go.sum
=> (fix): update go mod

command/harness/dlite/handler.go, command/harness/middleware.go
=> add /healthz endpoint in dlite mode

command/harness/step.go, internal/drivers/manager.go
In case of burst of vm setup request e.g. 1000 in a minute, a lot of setup calls were in waiting state for lock for more than 15 minutes. 
=> Reduce deadlock time in vm setup

command/config/config.go, go.mod, go.sum
=> Upgrade lite-engine version and go.mod

.drone.yml
Also removed the m1 pipeline - we need to figure the networking out on this.
=> fixes issue were mac builds werent' pointing at correct pool

.drone.yml, engine/compiler/compiler.go, engine/compiler/testdata/image.json, engine/compiler/testdata/plugins.json, engine/compiler/testdata/volumes.json, go.mod, go.sum
windows creation of folders in container and in bare metal<img width="1034" alt="image" src="https://user-images.githubusercontent.com/10402706/192759237-8b5738fc-3ccf-4945-8f9f-4ae43dbd9fe9.png">
linux test 
using https://github.com/tphoney/bash_plugin/blob/manifest_sftp/.drone.yml
=> (fix) single bind point for pipeline base folder

command/harness/pool.go, internal/drivers/azure/driver.go, internal/drivers/manager.go, internal/poolfile/config.go
=> (fix) better error messages when parsing pool file, azure especially

internal/drivers/azure/driver.go
=> (fix) improve destroy logs on azure

command/harness/pool.go, go.mod, go.sum, internal/drivers/google/driver.go, internal/encoder/encoder.go
=> (feat): upgrade dlite version to RC1 release

CHANGELOG.md
=> (maint): rc14 release prep

command/config/config.go, go.mod, go.sum
=> Upgrade lite-engine version

CHANGELOG.md
=> (maint): rc18 release prep

command/config/config.go, internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/lehelper/lehelper.go, types/types.go
=> Add plugin binary to cloudinit to support containerless plugin, action and bitrise steps

internal/cloudinit/cloudinit.go
=> (feat) adds support for bitrise plugin on mac

command/harness/step.go
=> Fix nil map in exported envs

command/harness/dlite/handler.go
=> Avoid crashing of runner in case of handler panics

CHANGELOG.md
=> release prep for v1.0.0-rc25

command/config/config.go
=> Upgrade plugin binary version

CHANGELOG.md
=> Prep for rc26

command/config/config.go, internal/drivers/google/driver.go, internal/drivers/google/option.go, internal/drivers/manager.go, internal/poolfile/config.go
=> Add hibernate support for gcp

command/command.go, command/config/config.go, command/harness/delegate/tester/README.md, command/harness/delegate/tester/client.go, command/harness/delegate/tester/tester.go, internal/drivers/manager.go, internal/drivers/noop/driver.go, internal/drivers/noop/option.go, internal/poolfile/config.go, types/types.go
=> Noop driver for scale testing runner

README.md, command/config/config.go, command/daemon/daemon.go, command/exec.go, engine/engine.go, go.mod, go.sum, internal/drivers/amazon/option.go, internal/drivers/anka/option.go, internal/drivers/ankabuild/option.go, internal/drivers/azure/option.go, internal/drivers/digitalocean/driver.go, internal/drivers/digitalocean/option.go, internal/drivers/google/option.go, internal/drivers/vmfusion/options.go, internal/poolfile/config.go
=> Fix start on digitalocean

CHANGELOG.md
=> release prep for rc29

internal/drivers/manager.go, types/types.go
=> Reduce lock time for hibernate support

command/config/account_pool_mapper.go, command/config/config.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/execute.go, command/harness/dlite/init.go, command/harness/pool_mapper.go, command/harness/setup.go, command/harness/step.go, store/database/ldb/stage_owners.go, store/database/sql/stage_owners.go, store/database/sql/stage_owners_sync.go, store/store.go
=> Add input config to map pools for an account to a separate value

command/config/config.go
=> [feat]: [CI-6692]: Upgrade lite engine

internal/drivers/google/driver.go
=> Fix cleanup on google create vm

command/config/config.go
=> upgrade lite engine version to increase health check timeout

CHANGELOG.md
=> (maint): rc32 prep

command/config/config.go
Bumping plugin binary to latest - contains a fix for GitHub actions on Mac.
=> bump plugin binary to latest

.drone.yml, command/harness/setup.go, internal/drivers/google/driver.go
=> Log serial console output for failed vm setup

command/harness/setup.go
=> add fallback pool logic for harness setup request

command/config/config.go, go.mod, go.sum
=> Upgrade Lite Engine

internal/drivers/ankabuild/driver.go
=> Handle error response correctly for anka vm get

command/config/config.go
=> Upgrade plugin version

command/config/config.go
=> update le version to 0.5.3

internal/poolfile/config.go
=> ignore errors while creating bare metal pool

command/config/config.go
=> update le to v0.5.4

internal/drivers/nomad/driver.go
=> destroy VM in case of error during polling

command/config/config.go, go.mod, go.sum
=> Upgrade lite-engine and plugin version in runner

command/config/config.go, internal/cloudinit/cloudinit.go
=> Add support for drone/plugin in windows

internal/drivers/nomad/driver.go
=> (feat): refactor nomad driver code

internal/drivers/nomad/driver.go
=> (feat): refactor destroy job

internal/cloudinit/cloudinit.go
added debug in linux init script
=> added debug in linux init script

command/config/config.go, command/exec.go, command/harness/delegate/tester/README.md, command/harness/setup.go, command/harness/step.go, command/setup/setup.go, engine/engine.go, go.mod, go.sum, internal/drivers/manager.go, internal/drivers/nomad/README.md, internal/drivers/nomad/driver.go, internal/drivers/nomad/noop_jobs.go, internal/drivers/nomad/option.go, internal/lehelper/lehelper.go, internal/poolfile/config.go
=> (feat): add noop functionality in nomad to do scale testing

internal/drivers/nomad/driver.go
=> change timeout for nomad

command/config/config.go
=> Upgrade plugin version for bitrise step env defaults

internal/drivers/nomad/driver.go
Added logging improvement, purge handling as job logs are vanishing after failure and force cleanup.
=> handle logging, cleanup on bare metal

internal/cloudinit/cloudinit.go
=> fix cloudinit script

command/config/config.go, command/harness/dlite/execute.go, command/harness/setup.go, command/harness/step.go, go.mod, go.sum, internal/cloudinit/cloudinit.go, internal/drivers/manager.go
=> Print only last 60k char logs from serial console output

internal/drivers/nomad/driver.go
=> fix destroy condition

command/config/config.go
=> Upgrade plugin to support github action on windows

internal/drivers/nomad/driver.go, internal/drivers/nomad/noop_jobs.go
=> Reduce retries in destroy call

internal/cloudinit/cloudinit.go, internal/drivers/nomad/option.go
=> add swap space of 10GB for bare metal

command/config/config.go, go.mod, go.sum
=> Update Lite Engine

go.mod, go.sum
=> update dlite version

command/config/config.go, command/harness/dlite/execute.go, command/harness/dlite/response.go, go.mod, go.sum
Added support for receiving artifacts from lite-engine.
=> Add artifact support in runner

go.mod, go.sum
=> Bump lite engine version

command/config/config.go
Created new plugin tag: https://github.com/drone/plugin/releases/tag/v0.3.2-beta
=> update plugin binary version

internal/drivers/nomad/driver.go
=> add check for resource job termination status before returning

internal/drivers/nomad/driver.go
=> add port forwarding before creating vm

command/config/config.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/cleanup.go, command/harness/helper.go, go.mod, go.sum, internal/cloudinit/cloudinit.go, internal/drivers/nomad/driver.go, internal/lehelper/lehelper.go, internal/oshelp/oshelp.go
=> add support for lite engine logs, add retries for port check

internal/cloudinit/cloudinit.go, internal/drivers/nomad/driver.go
=> fix: pass in lite engine logs path for bare metal

go.mod, go.sum
=> [CI-8549]: Fix bazel test rule logic for fallback, engine version bump

command/config/config.go, go.mod, go.sum
=> Bump lite-engine version

command/harness/step.go
=> fix lite engine timeout

command/harness/delegate/delegate.go
=> fix: register metrics in delegate flow

command/harness/context.go, command/harness/destroy.go, command/harness/dlite/dlite.go, command/harness/setup.go
=> add context to logs

internal/cloudinit/cloudinit.go
=> fix: [CI-8809]: Set machine variables for amazon linux script

command/config/config.go, command/harness/destroy.go, command/harness/dlite/dlite.go, command/harness/setup.go, go.mod, go.sum, metric/builds.go
=> add cpu and memory percentile as metrics in prometheus

command/harness/dlite/init.go, command/harness/dlite/response.go, command/harness/setup.go
=> Include pool driver used in Dlite VM setup response

internal/drivers/manager.go
=> fix: clean other pools if one fails

command/harness/context.go, command/harness/destroy.go, command/harness/setup.go, command/setup/setup.go, engine/engine.go, internal/drivers/manager.go, internal/drivers/nomad/driver.go, metric/builds.go, store/database/migrate/postgres/0005_update_table_instances_owner.up.sql, store/database/migrate/sqlite/0005_update_table_instances_owner.up.sql, store/database/sql/instances.go, types/types.go
=> add owner_id to instances, add metric to track running builds per owner

internal/drivers/manager.go
=> populate owner ID for new VM creation as well

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-7086]: Update LE version

internal/cloudinit/cloudinit.go
=> fix: [CI-8985]: tmate wrong removal 

command/harness/step.go
=> export github action step envs only for non container steps

command/harness/dlite/init.go, command/harness/dlite/response.go, command/harness/setup.go
This reverts commit ecd3782ceaf7369aad4d2fa8ff32918ca7c90f58.
=> Revert "Include pool driver used in Dlite VM setup response (#318)"

internal/cloudinit/cloudinit.go
=> fix: [CI-9031]:remove link and cp directly

internal/cloudinit/cloudinit.go
=> fix: dns resolv.conf modification

command/harness/delegate/delegate.go, command/harness/dlite/init.go, command/harness/dlite/response.go, command/harness/setup.go
=> Include pool driver used only in Dlite VM setup response

internal/cloudinit/cloudinit.go
=> [CI-9078]: Fix envman cloudinit script

internal/cloudinit/cloudinit.go
=> Hen/ci 9186 copy content of resolve.conf and append systemd resolver

command/config/config.go
=> CI-8134 updated lite engine version

command/config/config.go
=> [CI-9038]: Update lite-engine version

command/config/config.go
=> [CI-8554]: Update plugin version

command/config/config.go
=> [CI-9246]: Update LE version

command/config/config.go
=> update plugin binary

command/config/config.go
=> [CI-9043]: Update LE version

command/harness/dlite/cleanup.go, command/harness/dlite/ctx_state.go, command/harness/dlite/execute.go, command/harness/step.go
Added logic to abort and running steps when the cleanup request comes for a stage.
=> [CI-7513]: Abort any running steps when cleanup request is received

command/harness/setup.go
=> add retries for all cases during provisioning

command/harness/context.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/setup.go
=> fix: [CI-9385]: added more logs in destroy flow

command/harness/dlite/handler.go, command/harness/dlite/routes.go, command/harness/setup.go
Added recovery middleware for poller and remove nil pointer exception if hibernate start operation fails. If nil pointer comes, dlite restarts.
=> add recover middleware and some enhances

command/config/config.go
=> CI-9438 updated plugin binary version

command/config/config.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/cleanup.go, command/harness/dlite/execute.go, command/harness/dlite/init.go, command/harness/setup.go, command/harness/step.go, go.mod, go.sum
Runner changes to do execute step asynchronously
=> Runner changes for doing step status async

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-8932]: Update lite-engine

command/config/config.go, internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/drivers/nomad/driver.go, internal/drivers/nomad/option.go, internal/poolfile/config.go, types/types.go
=> feat: [CI-9698]: add support for pinning

command/harness/dlite/dlite.go, command/harness/setup.go, internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/drivers/util.go, internal/lehelper/lehelper.go, types/types.go
=> CI-9662: Added google dns for windows hosted

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-9766]: Update lite-engine

command/config/config.go
=> update le version to v0.5.34

command/harness/context.go, command/harness/dlite/cleanup.go, command/harness/dlite/execute.go, command/harness/dlite/init.go, command/harness/setup.go, metric/builds.go
=> [CI-9756]: Added metrics for dlite

internal/drivers/amazon/driver.go
=> add retries to amazon driver for setting tags

command/harness/ctx_state.go, command/harness/dlite/cleanup.go, command/harness/dlite/execute.go, command/harness/setup.go
=> break from fallback pool loop if context gets canceled

internal/cloudinit/cloudinit.go
=> Added cloud flare dns server

command/harness/setup.go, command/setup/setup.go, engine/engine.go, go.mod, go.sum, internal/drivers/manager.go, internal/drivers/util.go
=> CI-9787 added dns check logic

command/config/config.go
=> feat: [CI-9733]: upgraded le binary

internal/cloudinit/cloudinit.go
=> [CI-10143]: Add split test binary to linux

command/config/config.go
=> upgrade LE version

internal/cloudinit/cloudinit.go
=> change cloud init script

command/config/config.go
=> Update LE version

command/harness/setup.go
=> use no context during provisioning

command/config/config.go
added output command to rspec and python runners if user does not provided the command
added default path to python and ruby if not exist
=> Use default values for python and ruby test generation

command/config/config.go
=> Update lite engine version, test report refactor

internal/cloudinit/cloudinit.go
=> fix: [CI-9819]: update env var

command/harness/setup.go
Refactored code to handle fallback cleanups.
=> fix: [CI-9889]: Refactored code to handle fallback cleanups

internal/drivers/amazon/driver.go, internal/drivers/google/driver.go
=> fix: [CI-10299]: increased retry time in instance tagging

command/config/config.go
=> update le binary

command/config/config.go
This reverts commit 70646288e4233e4fc573132ffe47d90adce59516.
=> Revert "update le version (#391)"

command/harness/destroy.go
=> [CI-10370]: Remove duplicate logging in cleanup

internal/cloudinit/cloudinit.go
Reverts drone-runners/drone-runner-aws#362
=> Revert "fix: [CI-9819]: update env var"

command/harness/setup.go
=> feat: [CI-10749]: free tag for ci users

command/config/config.go, internal/drivers/nomad/driver.go, internal/drivers/nomad/option.go
=> use map for pinning

command/config/config.go
=> fix: [CI-10876]: fix python test extra filter

command/config/config.go, go.mod, go.sum
=> [CI-10373]: change ruby auto inject command to use workspace

internal/drivers/nomad/driver.go
=> add vm id and job id for error logs

command/config/config.go, go.mod, go.sum
=> Fix dlite unable to start, tidy go sum

command/config/config.go, go.mod, go.sum
=> use sh to invoke bundle

command/config/config.go, go.mod, go.sum
=> Fix Ruby auto inject logic on ubuntu machines

command/config/config.go, go.mod, go.sum
=> Ruby version use more compatible style

command/config/config.go, go.mod
=> change Ruby Helper file inject logic to pure frontload

command/config/config.go, go.mod, go.sum
=> Ruby inject

internal/drivers/nomad/driver.go
=> feat: [CI-10917]: fix frequency

command/config/config.go, go.mod, go.sum
=> Lite-engine version bump

command/config/config.go, go.mod, go.sum
=> Update Lite Engine version for python glob upgrade

command/config/config.go, go.mod, go.sum
=> CI-10058 Update LE

command/config/config.go, command/harness/dlite/execute.go, command/harness/dlite/response.go, go.mod, go.sum
=> Add optimization state to step response

command/config/config.go, go.mod, go.sum
=> feat: [CI-11274]: update le and dlite

command/config/config.go, go.mod, go.sum
=> verison bump - rspec glob update

internal/cloudinit/cloudinit.go
=> fix: [CI-11237]: modified retry commands

command/harness/dlite/init.go
=> feat: [CI-11071]: Increase Hosted CI init timeout to 30 minutes

command/config/config.go, command/daemon/daemon.go, command/harness/dlite/dlite.go, command/harness/dlite/handler.go, command/harness/pool.go, internal/drivers/distributed_manager.go, internal/drivers/google/driver.go, internal/drivers/google/option.go, internal/drivers/imanager.go, internal/drivers/manager.go, internal/poolfile/config.go
=> [CI-11511]: Remove normal pools, changed purger time for distributed dlite, add labels for gcp vms

command/config/config.go, internal/drivers/ankabuild/client.go, internal/drivers/ankabuild/driver.go, internal/drivers/ankabuild/option.go, internal/poolfile/config.go
=> feat:[CI-11620]:configure disk size using create vm api

command/config/config.go, go.mod, go.sum
=> update le to v0.5.65

command/config/config.go
=> feat:[CI-11620]: change yaml name for disk size

command/config/config.go, go.mod, go.sum
=> fix: [CI-11792]: updated lite-engine version

command/config/config.go, command/harness/dlite/dlite.go
Add internal endpoint for manager in dlite
=> add internal endpoint for manager

command/config/config.go
lite-engine release: https://github.com/harness/lite-engine/releases/tag/v0.5.67
=> Update lite-engine version

command/config/config.go, go.mod, go.sum
=> feat : [CI-11538]: LE bump

command/harness/dlite/cleanup.go, command/harness/dlite/execute.go, command/harness/dlite/init.go
=> fix: [CI-12553]: Added Account ID in logs to make debugging easier

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-12621]: Update lite-engine version

internal/drivers/nomad/driver.go
=> feat: [CI-12826]: use largebaremetalclass for large and xlarge resource class

internal/drivers/nomad/driver.go
=> fix: [CI-12826]: fix lint

internal/drivers/azure/driver.go
=> fix: [CI-11826]: Fixed ID - security type conflict

internal/drivers/azure/option.go, internal/poolfile/config.go
=> [feat]: [CI-13035]: Fix linting errors

chart/values.yaml
=> fix: [CI-13063]: Fix baremetal resources in charts

command/compile.go
=> fix: [CI-13052]: linting fix

command/harness/setup.go
=> fix: [CI-13158]: Add instance logs in batch

internal/cloudinit/cloudinit.go
=> fix: [CI-13084]: Install docker only for non hosted builds

chart/templates/deployment.yaml, command/config/config.go, command/harness/dlite/dlite.go, command/harness/dlite/handler.go
=> feat: [CI-12414]: Make distributed mode default for dlite

chart/values.yaml
=> fix: [OPS-23397]: Fix dlite chart to use loadbalancer url

chart/values.yaml
=> fix: [CI-12985]: Use internal manager endpoint

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-13544]: Update LE for CI_PARSE_SAVINGS changes

command/harness/dlite/dlite.go
=> [feat]:[CI-13601] Fix linting errors

command/harness/dlite/init.go, internal/drivers/imanager.go, internal/drivers/manager.go, internal/drivers/nomad/driver.go, internal/drivers/nomad/linux_virtualizer.go, internal/drivers/nomad/mac_virtualizer.go, internal/drivers/nomad/option.go, internal/drivers/nomad/virtualizer.go
=> feat: [CI-13619]: Lint fixed

internal/drivers/nomad/mac_virtualizer.go
=> feat: [CI-13619]: Run cloud init script as default anka user

internal/cloudinit/cloudinit.go
=> fix: [CI-13084]: Remove docker installation for ubuntu linux amd64

internal/cloudinit/cloudinit.go
=> feat: [CDE-238]: Remove docker and docker packages installation. Set DOCKER_API_VERSION=1.41

internal/drivers/nomad/mac_virtualizer.go
=> feat: [CI-13619]: Remove known hosts file to avoid too many auth errors

command/config/config.go, command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/drivers/nomad/linux_virtualizer.go, internal/lehelper/lehelper.go, types/types.go
For detection of build tool(gradle, bazel etc) and injecting config based on build tool for building cache, we created a seperate repository. Here we are writing some script to download the binaries.
As of now we are using this feature only for linux, and tested for both baremetal and gcp
=> feat: [CI-12961]: auto inject gradle and bazel config for build cache

internal/drivers/nomad/linux_virtualizer.go, types/types.go
=> fix: [CI-12959]: fix lint issues

internal/cloudinit/cloudinit.go
=> feat: [CDE-261]: Add back all gitspaces script except agent start cmd

internal/cloudinit/cloudinit.go
=> feat: [CDE-261]: Suppress both standard output and standard error by redirecting both to /dev/null in gitspaces init script

internal/cloudinit/cloudinit.go
=> fix: [CI-12959]: fixed the amazonLinuxScript

command/config/config.go, go.mod, go.sum, internal/drivers/nomad/linux_virtualizer.go, internal/drivers/nomad/mac_virtualizer.go, types/types.go
=> feat: [CI-13619]: Update LE and use expect instead of sshpass for tart

command/config/config.go
=> fix: [CI-14093]: use URLEncoding instead of RawURLEncoding for windows

command/config/config.go
=> fix: [CI-13938]: action multiline output variables

command/harness/setup.go, command/setup/setup.go, engine/engine.go, internal/cloudinit/cloudinit.go, internal/drivers/imanager.go, internal/drivers/manager.go, internal/drivers/nomad/driver.go, internal/drivers/nomad/linux_virtualizer.go, types/types.go
1. Optimize docker image pull by pointing the docker root directory to the external storage
2. Decouple pool.yaml storage from external storage config
=> feat: [CDE-333]: Optimize docker image pull; Decouple pool.yaml storage from external storage config

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-12024]: Update lite-engine to fix Savings UX bugs

internal/drivers/manager.go
=> fix: [CDE-344]: Default handling of labels for other drivers

command/config/config.go, command/harness/setup.go, internal/drivers/google/driver.go, internal/drivers/google/option.go, internal/poolfile/config.go, store/database/migrate/postgres/0011_update_table_instances_nested_virtualization.up.sql, store/database/sql/instances.go, types/types.go
=> feat: [CI-14261]: Added support of hardware acceleration in GCP VMs

command/config/config.go, go.mod, go.sum
=> [feat]: [CI-14538]: lite engine upgrade v0.5.84

app/drivers/google/driver.go, command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, command/harness/pool.go
=> feat: [PIPE-22742]: Refactor pool management

command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/cleanup.go
=> feat: [PIPE-23578]: Refactor runner to reuse VM tasks

app/drivers/amazon/driver.go, app/drivers/anka/driver.go, app/drivers/ankabuild/driver.go, app/drivers/azure/driver.go, app/drivers/digitalocean/driver.go, app/drivers/manager.go, app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/noop/driver.go, app/drivers/vmfusion/driver.go, command/config/config.go, command/harness/delegate/delegate.go, command/harness/pool.go, command/harness/setup.go, engine/compiler/compiler.go, engine/linter/linter.go, engine/linter/linter_test.go
=> fix: [CI-15476]: fix go-lint issue

app/drivers/nomad/mac_virtualizer.go
=> feat: [CI-15589]: support multiple execution for paypal

command/config/config.go, go.mod, go.sum
=> fix: [CI-15538]: Update lite-engine version to v0.5.89

go.mod, go.sum
=> fix: [CI-15405]: Update LE for network issue

app/drivers/nomad/driver.go
=> fix: [CI-15657]: Use LE Port instead for host port for healthcheck

app/drivers/nomad/driver.go
=> fix: [CI-15657]: Fix type cast

app/cloudinit/cloudinit.go, app/cloudinit/cloudinit_test.go, app/drivers/amazon/driver.go, app/drivers/anka/driver.go, app/drivers/ankabuild/driver.go, app/drivers/azure/driver.go, app/drivers/digitalocean/driver.go, app/drivers/google/driver.go, app/drivers/manager.go, app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/virtualizer.go, app/drivers/vmfusion/driver.go, app/lehelper/lehelper.go
- Add support for provisioning VM for gitspaces on GCS.
- Using the same script as CI, just the additional lines are to set up and run the gitspaces agent
=> feat: [CDE-511]: Add support for creation of gitspaces VMs on GCS

command/harness/helper.go, go.mod, go.sum
This PR upgrades the lite-engine dependency to v0.5.92.
=> feat: [PIPE-24093]: Upgrade to lite-engine v0.5.92

app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/virtualizer.go
=> fix: [CI-15735]: Fix port for healthcheck in linux and mac

command/config/config.go
=> fix: [CI-15731]: Updating DRONE_PLUGIN_BINARY_URI version.

app/drivers/nomad/driver.go
=> feat: [CI-15814]: Add alloc logs for job failures

app/drivers/google/driver.go
=> fix: [CDE-583]: Fix instance not found issue

app/drivers/nomad/driver.go
=> fix: [CI-16184]: Update Infor logs line for dlite

app/drivers/nomad/driver.go
=> fix: [PIPE-24681]: linting fix

command/harness/common.go, command/harness/helper.go, command/harness/setup.go, command/harness/step.go
=> feat: [CDE-616]: Make execute step stateless

command/harness/setup.go, metric/builds.go
=> feat:[CI-16186]: add machine address to build count

command/harness/setup.go
=> feat:[CI-16186]: fix

app/cloudinit/cloudinit.go, app/drivers/manager.go, app/drivers/nomad/linux_virtualizer.go, app/lehelper/lehelper.go, command/config/config.go, command/harness/dlite/dlite.go, types/types.go
Edit fallbacks for binaries which were getting downloaded from github. For fallback we will be using GCS.
=> feat: [CI-16199]: Add fallback for dependencies in cloudinit

app/drivers/google/driver.go, app/drivers/imanager.go, app/drivers/manager.go, command/harness/setup.go, command/setup/setup.go, engine/engine.go, types/types.go
=> feat: [CDE-635]: Make machine type configurable

command/harness/setup.go
=> feat: [CDE-616]: Don't log the whole response which now contains certs and keys

app/cloudinit/cloudinit.go
=> feat: [CDE-665]: Avoid race condition between docker restart in gitspace init script and lite engine docker operations

app/cloudinit/cloudinit.go, app/drivers/google/driver.go, app/drivers/imanager.go, app/drivers/manager.go, app/lehelper/lehelper.go, command/harness/setup.go, command/setup/setup.go, engine/engine.go, types/types.go
=> feat: [CI-16481]: Use google dns for GCP VMs

command/config/config.go
=> [feat]: [CI-16417]: plugin version upgrade

command/harness/dlite/init.go
=> feat: [CI-16686]: update init timeout for BYOI

app/drivers/imanager.go, app/drivers/manager.go, app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/option.go, app/drivers/nomad/virtualizer.go, app/poolfile/config.go, command/config/config.go, command/harness/setup.go, command/setup/setup.go, engine/engine.go, go.mod, go.sum, types/types.go
Enable BYOI (bring your own image) feature for hosted builds
=> feat: [CI-16702]: Enable BYOI (bring your own image) feature for hosted builds

app/drivers/nomad/mac_virtualizer.go
Added fixes and retry for BYOB
=> feat: [CI-16702]: Added fixes and retry for BYOB

app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/virtualizer.go
Delete older images if new image is provided. It does not delele default image on the machine
=> feat: [CI-16702]: Delete older images if new image is provided

app/drivers/nomad/driver.go, app/drivers/nomad/mac_virtualizer.go
=> feat: [CI-16702]: Lint fixes

app/drivers/nomad/linux_virtualizer.go
=> fix: [CI-16185]: Force delete firecracker vm

command/config/config.go, go.mod, go.sum
=> fix: [CI-16782]: Update LE Fix build tool path

command/config/config.go, go.mod, go.sum
=> feat:[CI-16808]: Updated liteengine tag

command/config/config.go, go.mod, go.sum
Lite engine changes: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/lite-engine/pulls/348
=> feat:[CI-16808]: Lite engine tag updated

command/config/config.go
=> feat: [CI-17118]: Update plugin binary version

app/drivers/nomad/driver.go
=> feat: [CI-17166]: reduce nomad job timeout

command/config/config.go
=> feat: [CI-17217]: Updating drone/plugin release version.

app/drivers/nomad/driver.go
=> feat: [OPS-44935]: Use PAID_POOL as default pool

command/config/config.go
=> [feat]: [CI-17150]: plugin update

command/harness/setup.go
=> feat: [CI-17257]: update log line with metadata fields for init

command/config/config.go, command/harness/setup.go, go.mod, go.sum
=> [feat]: [CI-17409]: Update LE to fix savings behaviour

command/harness/common/common.go, command/harness/destroy.go
=> feat: [CDE-753]: Validate only required keys for destroy request

app/drivers/google/driver.go, command/harness/destroy.go
=> feat: [CDE-753]: Don't wait for deletion in case of CI. Fix field names

app/drivers/imanager.go, app/drivers/manager.go, command/config/config.go, command/harness/dlite/dlite.go, command/harness/setup.go, types/types.go
=> feat: [CI-17423]: override health check timeout

README.md
=> feat: [CI-16869]: updated readme

app/drivers/nomad/linux_virtualizer.go
=> fix: [CI-17595]: Revert changes to delete firecracker vm directly

app/drivers/google/driver.go, app/drivers/google/util.go
=> feat: [CI-15708]: update image for vm image management caser

app/drivers/nomad/driver.go
=> fix:[CI-17635]: add sleep between retries.

app/drivers/amazon/driver.go
=> fix: [CI-17204]: added empty check on tags

app/drivers/amazon/driver.go
=> feat: [CDE-750]: fix lint issues

app/drivers/amazon/driver.go, app/drivers/amazon/option.go, app/drivers/google/driver.go, app/poolfile/config.go, command/config/config.go
=> feat: [CDE-813]: Support multiple AZs in AWS

command/harness/setup.go, metric/builds.go
=> feat: [CI-18050]: update metrics with imageName and imageVersion

app/cloudinit/cloudinit.go, app/cloudinit/user_data/amazon_linux, app/cloudinit/user_data/gitspaces_amazon_linux
=> feat: [CDE-849]: Separate cloudinit script for gitspaces and CI; Add run always and custom certs location for gitspaces

app/drivers/google/driver.go
- When GCP returns 404 during the destruction of the VM, it's not treated as an error
- Any other error status code is treated as an actual error and failure
=> feat: [CDE-816]: make google driver destroy idempotent, when VMs are not found.

app/cloudinit/cloudinit.go
Docker images was giving issue as it was not able to read the cloudinit scripts from the file. Hence using embed here.
=> fix: [CI-15437]: user_data fix

app/drivers/distributed_manager.go
Lock purger pool if warm pool size is > 0
=> fix: [CI-18151]: Lock purger pool if warm pool size is > 0

app/cloudinit/cloudinit.go, app/cloudinit/user_data/gcp_linux, app/drivers/google/driver.go, app/drivers/google/option.go, app/lehelper/lehelper.go, app/poolfile/config.go, command/config/config.go, types/types.go
Overview
This PR adds support for a new YAML flag is_c4d_lssd_enabled that conditionally enables or disables the NVME disk setup and related changes during GCP Linux VM provisioning. This allows for flexible configuration based on the VM specification, particularly for VMs with local SSD storage.
Changes
Added a new is_c4d_lssd_enabled boolean flag to the Google struct in the pool configuration
Modified the cloud-init template to conditionally include NVME disk setup based on this flag
Added proper propagation of the flag from the pool configuration through to the cloud-init template
Removed redundant enable_nvme_setup flag to simplify configuration
Streamlined logging in the cloud-init script generation
Why
Previously, NVME disk setup was always included in the cloud-init script for GCP …
=> feat: [CI-18056]: Add support to C4d Machine with NVMe Disk mount

app/drivers/nomad/driver.go, app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/noop_jobs.go, app/drivers/nomad/util.go, command/config/config.go, types/types.go
=> feat: [CI-17258]: move constant to config for nomad

command/config/config.go, go.mod, go.sum
=> feat: [CI-18220]: Update LE runner to capture new telemetry field

app/cloudinit/user_data/nomad_linux
=> fix: [CI-17784]: reset systemd for cloud init before docker restart

app/drivers/nomad/linux_virtualizer.go, app/drivers/nomad/mac_virtualizer.go, app/drivers/nomad/util.go
=> fix: [CI-18422]: Fix lints

app/drivers/google/driver.go
tested same with dlite
with this FF enabled and disabled: `CI_ENABLE_HOSTED_BETA_IMAGES` , `CI_ENABLE_HOSTED_IMAGE_MANAGEMENT`
=> fix: [CI-18445]: do not set image in config for gcp driver

app/drivers/distributed_manager.go
=> fix: [CI-17186]: fix query building order issue

command/config/config.go, go.mod, go.sum
=> fix:[CI-18565]: Updated liteengine

app/drivers/nomad/mac_virtualizer.go
before starting execution, if any image present with fqn name, it get deleted if image is not same as which is provided for run. It image is not available then it is pulled.
=> feat: [CI-18612]: delete image if fully Qualified on tart machine

app/drivers/manager.go, command/config/config.go, go.mod, go.sum
=> fix:[CI-18679]:update lite-engine tag to fix qa

go.mod, go.sum
=> fix: [PIPE-28910]: Upgrade to lite-engine v0.5.120

app/cloudinit/user_data/nomad_linux, app/cloudinit/user_data/ubuntu_linux, app/cloudinit/user_data/windows, app/drivers/nomad/linux_virtualizer.go, command/config/config.go, go.mod, go.sum
=> feat: [CI-18791]: Add cloud provider details to lite-engine

go.mod, go.sum
=> feat: [PIPE-29213]: Upgrade to lite-engine v0.5.124

app/drivers/manager.go, app/drivers/nomad/driver.go, command/harness/setup.go
1. Added logs in json format which will help in querying in cloud 
2. Used internal logger for any internal logs and kept UI logger separate.
3. Added hot pool logs to get information whether warm vm was picked or not.
=> feat: [CI-18759]: Improve logging and additionally added hotpool related logs

app/drivers/manager.go
=> feat: [CDE-1019]: Adding support for custom OS and Arch for gitspace VMs.

go.mod, go.sum
=> fix: [PIPE-29484]: Upgrade to lite-engine v0.5.125

command/config/config.go, command/harness/delegate/delegate.go, command/harness/dlite/dlite.go
=> feat:[CI-18842]: added the gradle.build.kts support

app/cloudinit/user_data/mac_arm64
=> fix: [CI-10615]: inject split binary to mac

command/config/config.go, command/harness/helper.go, go.mod, go.sum
=> feat: [PIPE-29761]: Lite Engine VersionBump

app/drivers/nomad/mac_virtualizer.go
1. Now using a local VM for BYOI instead of directly cloning from OCI Image.
2. Removed logic to tweak keychain for login, directly using tart env vars now
=> fix: [CI-19086]: Change logic for BYOI to use local VMs instead of directly from OCI

app/cloudinit/user_data/ubuntu_linux, app/drivers/amazon/driver.go, app/drivers/amazon/option.go, app/poolfile/config.go, command/config/config.go
Tested the script with c5ad.4xLarge machine: https://instances.vantage.sh/aws/ec2/c5ad.4xlarge?currency=USD
It provides us 16 cpu, and 32 GB memory and have nvme storage of 274GB, the doc specifies the 300 GB though.
=> feat: [CI-19014]: add support for aws c5ad machine

app/drivers/distributed_manager.go, app/drivers/manager.go, store/database/ldb/instances.go, store/database/sql/instances.go, store/database/sql/instances_sync.go, store/singleinstance/instances.go, store/store.go, types/types.go
This PR adds support for enabling global pool.
With this any pod can use a VM provisioned by any other pod.
=> feat: [CI-18946]: Enable global pool support

app/drivers/amazon/driver.go, app/drivers/anka/driver.go, app/drivers/ankabuild/driver.go, app/drivers/azure/driver.go, app/drivers/digitalocean/driver.go, app/drivers/distributed_manager.go, app/drivers/google/driver.go, app/drivers/imanager.go, app/drivers/manager.go, app/drivers/nomad/driver.go, app/drivers/noop/driver.go, app/drivers/pool.go, app/drivers/vmfusion/driver.go, command/daemon/daemon.go, command/exec.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/capacity.go, command/harness/dlite/cleanup.go, command/harness/dlite/dlite.go, command/harness/dlite/response.go, command/harness/dlite/routes.go, command/harness/setup.go, command/setup/setup.go, store/database/migrate/postgres/0012_create_table_capacity_reservation.up.sql, store/database/sql/capacity_reservation.go, store/database/sql/capacity_reservation_sync.go, store/database/wire.go, store/store.go, types/types.go
=> [feat]: [CI-18953]: Add capacity task
