drone-runners/drone-runner-aws

command/daemon/config.go, command/daemon/daemon.go, command/delegate/delegate.go, go.mod, go.sum, internal/cloudinit/cloudinit.go, internal/vmpool/cloudaws/config_file.go, internal/vmpool/cloudaws/pool.go, internal/vmpool/pool.go
1. Added support for aws key name. Key pair can be generated in aws and used for ssh /rdp to ec2 instances. 
2. Redirecting logs for lite-engine in windows vm to a file.
=> Support for aws key name & redirect logs for lite-engine

internal/cloudinit/cloudinit.go
Earlier, lite-engine started as part of cloud-init was not able to run git command as a sub-process. This commit installs git twice and sets up the choco profile that somehow fixes this issue.
=> Fix git command visibility in cloud-init

command/compile.go, command/daemon/config.go, command/daemon/daemon.go, command/delegate/config.go, command/delegate/delegate.go, command/exec.go, engine/compiler/compiler.go, engine/resource/volume.go, engine/resource/volume_test.go, go.mod
This support already exists in the docker and k8s runners.
Ref: https://docs.drone.io/runner/nomad/configuration/reference/drone-runner-volumes/
Sample PR for the k8s runner: https://github.com/drone-runners/drone-runner-kube/pull/24
In the above implementation for k8s, map is used to represent volumes but there can be duplicate sources (eg source 'a' mapping to destinations 'b' and 'c'). Hence changed that to a list here.
Will fix this in the docker and kubernetes runners as well.
=> Add support for DRONE_RUNNER_VOLUMES in the Drone AWS runner.

command/exec.go, command/setup/setup.go, engine/engine.go, store/database/wire.go, store/singleinstance/instances.go, test_files/compiler/drone_ubuntu.yml
delegate test
``` 
➜  go-scm git:(no_project) curl -d '{"id": "unique-stage-id","correlation_id":"abc1","pool_id":"ubuntu", "setup_request": {"network": {"id":"drone"}, "platform": { "os":"ubuntu" }}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/setup
{"instance_id":"i-0ad791adb306c1f05","ip_address":"3.145.7.123"}
➜  go-scm git:(no_project) curl -d '{"id":"unique-stage-id","instance_id":"i-0ad791adb306c1f05","pool_id":"ubuntu","correlation_id":"abc1", "start_step_request":{"id":"step4", "image": "alpine:3.11", "working_dir":"/tmp", "run":{"commands":["sleep 30"], "entrypoint":["sh", "-c"]}}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/step
{"exited":true}
➜  go-scm git:(no_project) curl -d …
```
=> (feat) have a single instance db for exec / setup.

command/daemon/daemon.go, command/exec.go, command/setup/setup.go, internal/poolfile/config.go
```
➜  drone-runner-aws git:(DRON-281) sudo  ntpdate pool.ntp.org
17 May 11:22:59 ntpdate[15251]: step time server 195.171.43.12 offset -0.881551 sec
➜  drone-runner-aws git:(DRON-281) curl -d '{"id": "unique-stage-id","correlation_id":"abc1","pool_id":"ubuntu", "setup_request": {"network": {"id":"drone"}, "platform": { "os":"ubuntu" }}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/setup
{"instance_id":"i-0efdc98a593c81778","ip_address":"3.134.88.219"}
➜  drone-runner-aws git:(DRON-281) curl -d '{"id":"unique-stage-id","instance_id":"i-0efdc98a593c81778","pool_id":"ubuntu","correlation_id":"abc1", "start_step_request":{"id":"step4", "image": "alpine:3.11", "working_dir":"/tmp", "run":{"commands":["sleep 30"], "entrypoint":["sh", "-c"]}}}' -H "Content-Type: …
```
=> (DRON-281) daemon can start using env vars

.drone.yml, command/config/config.go, internal/poolfile/config.go
```
➜  drone-runner-aws git:(min_max) ✗ date
Tue May 17 14:35:11 BST 2022
➜  drone-runner-aws git:(min_max) ✗ curl -d '{"id": "unique-stage-id","correlation_id":"abc1","pool_id":"ubuntu", "setup_request": {"network": {"id":"drone"}, "platform": { "os":"ubuntu" }}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/setup
{"error_msg":"pool not defined"}
➜  drone-runner-aws git:(min_max) ✗ curl -d '{"id": "unique-stage-id","correlation_id":"abc1","pool_id":"test_pool", "setup_request": {"network": {"id":"drone"}, "platform": { "os":"ubuntu" }}}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/setup
{"instance_id":"i-044ead40274a7673a","ip_address":"3.139.61.255"}
➜  drone-runner-aws git:(min_max) ✗ curl -d …
```
=> (feat) allow min/max pool size to be set from env

command/config/config.go, command/daemon/daemon.go, engine/engine.go, internal/drivers/anka/pool.go, internal/drivers/vmfusion/pool.go
* adds purger to daemon
* fixes the issue, where destroy, was getting called twice, once as a goroutine & in runner.go execer command
* adds context to command calls on anka - was causing failures not to surface, threads getting lost
tickets:
- https://harness.atlassian.net/browse/DRON-285
- https://harness.atlassian.net/browse/DRON-283
Delegate Tests:
=> (fixes)  dron-285 - fixes issues with anka & adds purger to daemon

command/delegate/delegate.go, store/database/migrate/postgres/0002_create_table_instances_stageowner.up.sql, store/database/migrate/sqlite/0002_create_table_instances_stageowner.up.sql, store/database/stage_owners.go, store/database/stage_owners_sync.go, store/database/wire.go, store/store.go, types/types.go
Currently only one runner can be the owner of a specific pool in harness CIE. For OSX builds, this is a big limitation since only 2 parallel builds can happen for a pipeline.
To fix this limitation, this change is required. Without this change, cleanup is not guaranteed to happen. Pipeline can be aborted at any time. In case it is aborted just a second after starting up, setup & cleanup call can happen in parallel. We use capability check in CIE to determine which delegate needs to execute a VM setup task. If more than 2 runners are responsible for same pool, stage ownership is added to pool owner api so that cleanup call gets assigned to correct delegate.
=> Add stage owner support in pool ownership api

command/harness/dlite/dlite.go, go.mod, go.sum
=> moved token creation and updation to dlite

command/harness/dlite/execute.go, command/harness/dlite/init.go, internal/drivers/google/driver.go, internal/drivers/google/util.go, internal/drivers/google/util_test.go, internal/drivers/manager.go, main.go
In case pool size of more than 1 was selected, instance name collision was taking place which was failing instance creation.
`ERRO[0009] manager: failed to create instance            error="googleapi: Error 409: The resource 'projects/ci-play/zones/us-central1-a/instances/shubhamagrawal-ubuntu-gcp-shubham-1658843098' already exists, alreadyExists"`
Also, removed spaces in instance name. 
=> Fix instance name in gcp runner

command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, command/harness/pool.go
=> start publishing tags based on supported os/arch

go.mod, go.sum, internal/drivers/manager.go
=> Fix cleanup of instances

docker/Dockerfile.linux.amd64, docker/Dockerfile.linux.arm64
Curl is required for enabling/disabling maintenance mode on dlite running in a kubernetes cluster for hosted vms.
=> Add curl tool to the docker image

command/config/config.go, internal/cloudinit/cloudinit.go
Host machine environment variables present on bootup are not present in cloud init script process. Hence, environment variables of host machine are not set. So, tools installed on host machine are not accessible to steps as well. 
This PR sets the environment variables of host machine to file /root/.env for ubuntu which is read by lite-engine and set appropriately.
=> Set machine environment variables to lite-engine

command/config/config.go, command/daemon/daemon.go, command/exec.go, command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, command/setup/setup.go, internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/lehelper/lehelper.go, types/types.go
This PR downloads split test binary for Ubuntu Linux VMs where the driver is either delegate or dlite. It is downloaded from a GCS bucket where the binary is uploaded by the CIE Build Release pipelines. This is achieved by updating the cloudinit script for Ubuntu VMs which means the binary will be downloaded as part of VM startup. It also includes a minor refactor where the environment config is passed to the driver instead of individual parameters as suggested which includes updating a few structs as well.
Evidence for binary being present (downloaded) in the VM:
=> (feat) Inject split test binary for Linux VMs (CIE)

.drone.yml, internal/drivers/ankabuild/driver.go
If lots of VMS were created at once - the machine name wasn't unique breaking the constraint
=> (bug) - fixes issue where machine name wasn't unique for anka build

command/harness/scripts/clone.go
Clone script failed on harness due to trying to write to /etc/ which is protected on Mac.
=> (bug) ssh Mac clone can't not write to ssh known hosts

command/harness/scripts/clone.go
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: Permission bits for '/Users/anka/.netrc' should be 0600, but are 644
=> fix permission of .netrc file

command/config/config.go
This change upgrades the lite engine to v0.4.8 version. 
The v0.4.8 version has downgraded version of docker client, this change was necessary in order for gcp vms to work with windows. The reason being Vms were at a lower docker client version which was resulting in issues for windows vms.
=> Upgraded lite engine to v0.4.8 (where docker client is downgraded)

command/harness/destroy.go
If a destroy task comes while an initialize task is ongoing, destroy was not getting processed sometimes. This PR adds exponential backoff retries to the destroy task so that it completes.
=> add retries on Harness destroy task

command/config/config.go
If the hostname starts with a number (example `0b68be1f3feb`), GCP API call fails with the below error
`googleapi: Error 400: Invalid value for field 'resource.name': '0b68be1f3feb-ubuntu-gcp-pgfir7t8-t0n4f'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'`
=> Add prefix to hostname while setting default runner name

internal/cloudinit/cloudinit.go
Added envman binary in cloudinit. This binary is used by bitrise plugins to support output variables.
=> [CI-9078]: Added envman binary in cloudinit

internal/lehelper/lehelper.go
Without a custom cloudinit a Windows pool was attempting to start with the linux cloudinit. Check `opts.Platform.OS` not `opts.OS` to get the type.
=> Fix default cloudinit for non-linux pools

internal/drivers/google/driver.go
We saw some executions where the gcp zone operation get call is getting stuck for default timeout (10m). Have added smaller timeout on that api call so that it can retry again.
=> add timeout for gcp zone operation get

internal/cloudinit/cloudinit.go
Progressbar significantly increases the download time during cloud init. This pr disables it. I have noticed that it helps reducing overall cloud init time by 120+ seconds 
=> feat: [CI-11955]: Updated windows cloud init

internal/cloudinit/cloudinit.go
Why this change?
> Customer has a restriction that they can only access https urls.
Wouldn't it break for already existing customers who donot have https connectivity?
> For downloading le and plugin we use https only, it would have never worked for them in the first place.
Tested for both aws and gcp windows vms.
=> fix: [CI-11955]: add https to scoop script

internal/drivers/distributed_manager.go, internal/drivers/manager.go, store/database/migrate/postgres/0008_create_index_instances_pool_state_started_at.up.sql, store/database/sql/instances.go
Fixed following things with this PR:
1. We were not using the instance_pool field to filter for the pool for which purger was running. Due to this for any other pool too we would have fetched the VM from DB but eventually it will fail since driver won't match for it.
2. When we bring up a VM from hibernate then we don't update instance_started due to which there are chances that purger can pick it up since a VM can be in hibernate for a very long time as well.
=> fix distributed purger to use same pool 

command/config/config.go, go.mod, go.sum
Lite engine version upgrade to 0.5.70.
This version consists of changes for supporting output variables as secrets for plugins to export
=> [fix]: [CI-12562]: lite-engine upgrade

command/config/config.go, internal/drivers/azure/driver.go, internal/drivers/azure/option.go, internal/poolfile/config.go
We are supporting spinning up of Azure VM with custom image via pool.yml, initially it was supported for marketplace image only. 
Cases Tested
1. Keep the yaml as same as old one (backward compatibility ensured). VM was spinned up. (Image used here was market price image)
2. Changed the yaml by removing the parameters like sku, version, publisher, offer (generally used for market price image) and introduced new parameter "id" which is the full path of custom image. 
3. Trying to fill the parameters like sku, version, publisher, offer with custom image params, it will not work as it is not published image. Those params we won't find in VM spinned up custom image (By looking json response of VM)
=> fix: [CI-11826]: Added support Azure VM spin up for custom image

command/compile.go, command/daemon/daemon.go, command/exec.go, command/harness/pool.go, command/setup/setup.go, engine/compiler/compiler_test.go, internal/poolfile/config.go
We need to pick this password from env var, currently it is being set in pool yaml only and it's value is visible in gcp pod yaml. With this change, we can delete the value from pool yaml and set it as env variable(ANKA_BUILD_TOKEN) instead, which we can mark as secret.
=> fix: [CI-13052]: take anka authtoken from env

internal/cloudinit/cloudinit.go
Git comes already installed with hosted vms image, hence put a if condition to not do it for hosted.
The default git version on vms is 2.42.0.windows.2 while scoop installs 2.44.0.windows.1. No major changes between these two.
Removed a condition in script that was always failing and taking some time due to syntax error.
Tested on aws and gcp.
=> feat: [CI-11955]: removed scoop from dlite windows cloudinit

command/config/config.go, command/harness/dlite/execute.go, go.mod, go.sum
Currently optimization state is not returned for a failed step. This should be done to make sure cache intel FULL_RUN is saved since cache intel is a FULL_RUN if the restore-cache-harness step fails
Tested on local
FULL_RUN (where restore step fails)
We can see that we are returning the optimization state
Optimized Run
=> [feat]: [CI-13579]: Return Optimization state for Failed Restore Cache Step

internal/drivers/google/driver.go
If trimmed name starts with a '-' character, gcp throws an error, hence replacing it with a d.
=> fix: [CI-14221]: fix gcp instance name issue

internal/drivers/distributed_manager.go, internal/drivers/manager.go, internal/drivers/nomad/driver.go, internal/drivers/nomad/linux_virtualizer.go, store/database/ldb/instances.go, store/database/migrate/postgres/0010_update_table_instances_labels.up.sql, store/database/migrate/sqlite/0008_update_table_instances_labels.up.sql, store/database/sql/instances.go, types/types.go
1. Storing labels in the instance table as well as setting them in the VM in the ignite run command
2. Added migration to add this column with default {"retain":"false"}
3. CI instances/VMs will have {"retain":"false"} label
4. CDE instances/VMs will have {"retain":"false"} label
5. The list instance query from the purger would have {"retain":"false"} matchlabels to match only CI instances and avoid cleanup of CDE instances/VMs
=> feat: [CDE-344]: Skip CDE VMs in the dlite instance purger with the help of labels on the instance/VM

internal/cloudinit/cloudinit.go, internal/drivers/manager.go, internal/drivers/nomad/linux_virtualizer.go, types/types.go
Since we wanted to send more params for container name, tag, image etc, instead of adding so many params, thought of sending the whole script and appending to the existing one in cloudinit.go
To keep it backward compatible, I haven't removed any existing params.
This would be the script coming from CDE Manager with all the replaced values.
```
groupadd docker
mkdir -p /mnt/disks/mountdevcontainer/gitspace
export DOCKER_API_VERSION={{ .AgentDockerAPIVersion }}
echo "Updating docker root dir"
systemctl stop docker
mkdir -p /mnt/disks/mountdevcontainer/docker
tee /etc/docker/daemon.json <<EOF
{
"data-root": "/mnt/disks/mountdevcontainer/docker"
}
EOF
systemctl start docker
echo "Successfully updated docker root dir"
echo "starting gitspaces agent"
if docker ps -a --filter "name={{ …
```
=> feat: [CDE-365]: Send the whole gitspace agent script instead of individual params

app/drivers/google/driver.go, app/drivers/imanager.go, app/drivers/manager.go, command/harness/common.go, command/harness/delegate/delegate.go, command/harness/destroy.go, command/harness/dlite/init.go, command/harness/dlite/response.go, command/harness/helper.go, command/harness/setup.go, command/setup/setup.go, engine/engine.go, types/types.go
- Passing zone in create/setup requests. If present, a random zone won't be selected. (CI requests will continue with random zone selection)
- This instance info is saved in the DB of cde-manager and passed in the destroy request.
- Destroy requests will fetch instances from DB only when not present in the request. (CI requests will continue to fetch )
- CDE requests use the passed information from the destroy requests instead of relying on the instance record in DB
- CI requests continue to use the instance stored in DB in the destroy/cleanup request
=> feat: [CDE-583]: Make destroy operation stateless by passing instance details instead of relying on db / in memory storage

app/drivers/google/driver.go, app/drivers/manager.go, command/harness/common.go, command/harness/delegate/delegate.go, command/harness/helper.go, command/harness/setup.go, types/types.go
1. Create Disk
- Create (if required) and attach the persistent disk to the VM.
- Wait for the disk to be created and then initiate instance creation.
- Pass storage type (example: "pd-balanced")
- storage_identifier supports a comma-separated list of identifiers, to support 2 separate disks (1 for gitspace and 1 for docker) in the future.
2. Delete Disk
- Delete the disk on Delete Gitspace (StorageCleanupType.DELETE).
- Disk would retained in case of Stop Gitspace (StorageCleanupType.DETACH).
- If the disk needs to be deleted, wait for instance deletion to complete and then hit the delete disk API.
- Add storage_identifier in instance info (This will be sent in the destroy request to identify the disk and delete it)
- Pass StorageCleanupType in VMCleanupRequest
3. Skip CDE VMs from …
=> feat: [CDE-585]: Support creation and attaching of persistent disks

command/harness/setup.go
The default timeout for Init Step VM is 5 min,  In this PR this is updated.
For Windows it is kept 5 mins and for Linux and Mac os it is kept 3 min.
Below are testing details image:
=> fix: [CI-16188]: update health timeout check for windows and other OS

app/drivers/vmfusion/syscall_unix.go, app/drivers/vmfusion/syscall_windows.go, app/drivers/vmfusion/utils.go
The runner would not build on windows before since Umask is not supported on windows. This lets the runner build on windows.
env GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="x86_64-w64-mingw32-gcc" go build generates windows builds
=> feat: [PIPE-24820]: Remove syscall.Umask for windows builds

app/cloudinit/cloudinit.go, app/drivers/nomad/driver.go
Add stderr logs for failure tasks in a job.
```
time="2025-02-07T18:05:57+05:30" level=error msg="scheduler: successfully failed task stderr logs" init_job_id=init_job_oyjhkd2yhap4xcgru0tm node_class=CI_QA node_ip=15.204.85.27 node_port=26739 resource_job_id=init_job_resources_oyjhkd2yhap4xcgru0tm stage_runtime_id=s4JFBtrkR5eFBYVT3OE_YA stderr_data="--2025-02-07 12:35:35--  https://github.com/harness/lite-engineee/releases/download/v0.5.94//lite-engine-linux-amd64\nResolving github.com (github.com)... 140.82.116.3\nConnecting to github.com (github.com)|140.82.116.3|:443... connected.\nHTTP request sent, awaiting response... 404 Not Found\nGiving up.\n\nSetting --output-document (outputdocument) to /usr/bin/lite-engine\nDEBUG output created by Wget 1.21.2 on linux-gnu.\n\nReading HSTS …
```
=> feat: [CI-16207]: Add stderr logs for failed tasks

command/config/config.go, go.mod, go.sum
lite-engine buil tag: https://github.com/harness/lite-engine/commits/v0.5.95
=> feat: [CI-16060]: Update lite-engine version to v0.5.95

app/cloudinit/cloudinit.go
For the PayPal POV, we need to support remote debugging on Mac. This requires compiling tmate statically on Mac and pulling it via the CloudInit script.
=> feat:[CI-16771]: Add tmate compiled for arm

app/drivers/amazon/driver.go
This has been tested by using the gp3 image and making sure an encrypted disk is created
=> [feat]: [CI-16881]: Currently encypted disks is only supported for io1 disk type. Adding this support for all aws disk types

app/cloudinit/cloudinit.go
Tested with long running pipelines, the DNS resolution is working fine.
=> fix: [CI-16953]: Force DNS queries using google

command/harness/setup.go
Log the VM setup time in the init logs
=> feat: [CI-17257]: capture vm setup time in init logs

app/drivers/nomad/linux_virtualizer.go
Add healthcheck for ignite exec before running cloudinit
=> fix: [CI-17303]: Enable ignite healthcheck before running cloudinit

app/drivers/manager.go, command/harness/setup.go
#Description 
We saw that we are hibernating vms even if the lite engine connectivity check fails. Due to which, we will see init failures when we provision the. This pr deletes the vms which failed connectivity check before hibernation.
=> feat: [CI-17310]: destroy if hibernate connectivity fails

README.md, app/drivers/manager.go, command/config/config.go, command/harness/delegate/delegate.go, command/harness/setup.go, types/types.go
This pr attempts to support running multiple replicas of vm runner in a kubernetes cluster while delegate being a single one. We are introducing this flag DRONE_RUNNER_HA which should be enabled in case we are deploying multiple replicas.
Load tested with one delegate and 8 runner replicas on kubernetes https://app.harness.io/ng/account/9UuUfLwaQ-6ZowvbG7qtLQ/module/ci/orgs/default/projects/RaghavTest/pipelines/raghavnginxbuild/executions/CB1dIPBSSv2O-Dkegv0EhA/pipeline?stage=5te4Ng8xRzCb3fqeyN7dMg&stageExecId=W3feAM0ZTCCuUzFHtijzXA
https://app.harness.io/ng/account/9UuUfLwaQ-6ZowvbG7qtLQ/module/ci/orgs/default/projects/RaghavTest/pipelines/raghavnginxbuild/executions/PcC7PawGRJyvbMttJ54MxA/pipeline
=> feat: [CI-16869]: HA for vm runner

app/cloudinit/cloudinit.go
1. changes are done only in linux Script & gitspacesLinuxScript (Baremetal) for plugin and le binaries 
2. All the other places primary source download fails in 3 retries already 
Testing : 
tested by giving primary url wrong link and verified 3 times download retry 
tested primary source download post script changes 
=> [feat]: [CI-17465]: reducing retry count to fail fast from github

command/config/config.go, command/harness/delegate/delegate.go, command/harness/dlite/dlite.go, go.mod, go.sum
Description- 
This change include the new LE v0.5.109
and auto-injection v1.0.7 for maven build cache.
Testing done- tested maven/gradle build cache with the LE/runner version - working as expected with autoinjection.
=> fix: [CI-16878]: update LE for maven build cache

app/drivers/amazon/driver.go, app/drivers/amazon/option.go, app/poolfile/config.go, command/config/config.go
Field for adding tags to the aws volumes.
```
version: "1"
instances:
- name: linux-amd64
type: amazon
spec:
disk:
tags: #new field
volumekey: volumeValue
key1: value2
size: 100
kms_key_id: 95294cb8-24d7-4994-998e-5850945171da
```
Here the volumes obtained by this pool will have the tags volumekey: volumeValue and key1: value2.
Tested with aws with encrypted and non encrypted volumes.
=> feat: [CI-17204]: volumes tags aws

app/drivers/amazon/driver.go, app/drivers/google/driver.go, app/drivers/google/util.go, app/drivers/manager.go
* Add support to configure vm image from `/setup` request param
* add support to configure vm image from `/setup` request param for aws driver.
* If image is not provided, we will use the image from pool.yaml 
* add support to directly send image path for gcp driver 
Created VM with image given in the request for aws ✅ 
* setup request contains `ami-0001c5332b86ed44b` while pool.yml contains `ami-084568db4383264d4` image 
* VM is provisioned with `ami-0001c5332b86ed44b`
Created VM with image given in the request for gcp ✅ 
* request with image `projects/debian-cloud/global/images/debian-11-bullseye-v20250709`
* VM successfully created
If you …
=> feat: [CDE-828]: use configurable image for vms for gitspace

command/harness/setup.go
This change adds detailed logs to GCP for both **success** and **failure** scenarios during the init step.  
The following information will now be logged:
- `accountId`
- `buildId`
- `pipelineId`
- `orgId`
- `projectId`
- `stageRuntimeId`
- `taskId`
- `isRunner`
---
---
=> feat: [CI-18029]: Added logs for GCP incase of success and fail init step

app/drivers/google/driver.go
Added a Metadata of pipeline in VM Metadata, below field will be listed:
- harness-account-id
- harness-pool-name
- harness-runner-name
- harness-resource-class
- harness-platform-os
- harness-platform-arch
=> feat: [CI-18607]: add info of pipeline build in VM metadata

app/drivers/google/driver.go, app/drivers/manager.go
- Call DestroyInstanceAndStorage to wait for instance deletion
- Don't use gitspace config identifier as the VM name. Use it just as a label
=> feat: [CDE-1026]: Gitspace VM name and infra reset updates

app/drivers/nomad/linux_virtualizer.go
Add ignite wait check in poststop hook. This only runs the task once all the main tasks are completed.
=> fix: [CI-17303]: Add ignite wait check in poststop hook

command/harness/setup.go
- **`harness_ci_pipeline_execution_errors_total`**
- Now records **which pool** the failure occurred in.
- Previously it only recorded the **requested pool**.
- Updated to **capture all failed pools**, not just one.
- **`harness_ci_runner_wait_duration_seconds`**
- Fixed to record the **actual wait time**.
- Previously it was capturing the **overall  time** instead.
Wait count of different pools in case of fallback 
Failed count of failed pools
=> feat: [CI-18793]: Updated metrics to capture correct wait time and failed counts

app/drivers/amazon/driver.go
Added tags for AWS VM instances to improve debugging and provide better visibility.  
**Tags added:**
- `harness-account-id`
- `harness-pool-name`
- `harness-runner-name`
- `harness-resource-class`
- `harness-platform-os`
- `harness-platform-arch`
These tags will now be visible on the VM after provisioning, making it easier to trace and debug issues.  
**Screenshots:**
---
Thank you for creating a pull request! To help us review and merge, please ensure that your PR adheres to the following:
=> feat: [CI-19013]: Added vm tags for aws similar to gcp

app/drivers/nomad/driver.go, command/config/config.go
If the baremetal init fails we try to run a destroy job for the vm. We poll for the job status for 3 minutes for that. Currently that logic is sync and blocks the thread from trying to initialize the vm in the fallback pool. 2 things I am doing to speed things up
1. Reduce timeout from 3m to 1m
2. Make the cleanup logic async so it doesnt block the fallback logic
Screenshot showing there is now no time diff between nomad init failure and gcp init start
=> [feat]: [CI-19068]: Reduce Init Time Incase of Fallback

command/harness/setup.go, metric/builds.go
Currently we only have logs and metrics for init time per pool. This is not reflective of what the user sees when there are fallbacks since init request goes to multiple pool. I have added a new grafana metrics and logging for total init time for a VM
=> [feat]: [CI-19223]: Add metrics and log for total init time
